// This file is auto-generated by @hey-api/openapi-ts

/**
 * BearerResponse
 */
export type BearerResponse = {
  /**
   * Access Token
   */
  access_token: string;
  /**
   * Token Type
   */
  token_type: string;
};

/**
 * Body_auth-reset:forgot_password
 */
export type BodyAuthResetForgotPassword = {
  /**
   * Email
   */
  email: string;
};

/**
 * Body_auth-reset:reset_password
 */
export type BodyAuthResetResetPassword = {
  /**
   * Token
   */
  token: string;
  /**
   * Password
   */
  password: string;
};

/**
 * Body_auth-verify:request-token
 */
export type BodyAuthVerifyRequestToken = {
  /**
   * Email
   */
  email: string;
};

/**
 * Body_auth-verify:verify
 */
export type BodyAuthVerifyVerify = {
  /**
   * Token
   */
  token: string;
};

/**
 * Body_logs-upload_log_file
 */
export type BodyLogsUploadLogFile = {
  /**
   * File
   */
  file: Blob | File;
  /**
   * Model
   */
  model?: string;
};

/**
 * ErrorModel
 */
export type ErrorModel = {
  /**
   * Detail
   */
  detail:
    | string
    | {
        [key: string]: string;
      };
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
  /**
   * Detail
   */
  detail?: Array<ValidationError>;
};

/**
 * ItemCreate
 */
export type ItemCreate = {
  /**
   * Name
   */
  name: string;
  /**
   * Description
   */
  description?: string | null;
  /**
   * Quantity
   */
  quantity?: number | null;
};

/**
 * ItemRead
 */
export type ItemRead = {
  /**
   * Name
   */
  name: string;
  /**
   * Description
   */
  description?: string | null;
  /**
   * Quantity
   */
  quantity?: number | null;
  /**
   * Id
   */
  id: string;
  /**
   * User Id
   */
  user_id: string;
};

/**
 * LogEntryRead
 */
export type LogEntryRead = {
  /**
   * Id
   */
  id: string;
  /**
   * Log File Id
   */
  log_file_id: string;
  /**
   * Timestamp
   */
  timestamp?: string | null;
  /**
   * Source Ip
   */
  source_ip?: string | null;
  /**
   * User Agent
   */
  user_agent?: string | null;
  /**
   * Action
   */
  action?: string | null;
  /**
   * Url
   */
  url?: string | null;
  /**
   * Method
   */
  method?: string | null;
  /**
   * Status Code
   */
  status_code?: number | null;
  /**
   * Bytes Sent
   */
  bytes_sent?: number | null;
  /**
   * Url Category
   */
  url_category?: string | null;
  /**
   * Threat Name
   */
  threat_name?: string | null;
  /**
   * User Login
   */
  user_login?: string | null;
  /**
   * Raw Line
   */
  raw_line?: string | null;
  /**
   * Is Anomaly
   */
  is_anomaly: boolean;
  /**
   * Anomaly Score
   */
  anomaly_score?: number | null;
  /**
   * Anomaly Reason
   */
  anomaly_reason?: string | null;
};

/**
 * LogFileRead
 */
export type LogFileRead = {
  /**
   * Id
   */
  id: string;
  /**
   * Filename
   */
  filename: string;
  /**
   * Uploaded At
   */
  uploaded_at: string;
  /**
   * Total Entries
   */
  total_entries: number;
  /**
   * Anomaly Count
   */
  anomaly_count: number;
};

/**
 * LogFileSummary
 */
export type LogFileSummary = {
  file: LogFileRead;
  /**
   * Timeline
   */
  timeline: Array<TimelineBucket>;
  /**
   * Top Source Ips
   */
  top_source_ips: Array<TopIp>;
  /**
   * Top Actions
   */
  top_actions: {
    [key: string]: number;
  };
  /**
   * Top Categories
   */
  top_categories: {
    [key: string]: number;
  };
  /**
   * Ai Explanation
   */
  ai_explanation?: string | null;
};

/**
 * Page[ItemRead]
 */
export type PageItemRead = {
  /**
   * Items
   */
  items: Array<ItemRead>;
  /**
   * Total
   */
  total?: number | null;
  /**
   * Page
   */
  page: number | null;
  /**
   * Size
   */
  size: number | null;
  /**
   * Pages
   */
  pages?: number | null;
};

/**
 * Page[LogEntryRead]
 */
export type PageLogEntryRead = {
  /**
   * Items
   */
  items: Array<LogEntryRead>;
  /**
   * Total
   */
  total?: number | null;
  /**
   * Page
   */
  page: number | null;
  /**
   * Size
   */
  size: number | null;
  /**
   * Pages
   */
  pages?: number | null;
};

/**
 * Page[LogFileRead]
 */
export type PageLogFileRead = {
  /**
   * Items
   */
  items: Array<LogFileRead>;
  /**
   * Total
   */
  total?: number | null;
  /**
   * Page
   */
  page: number | null;
  /**
   * Size
   */
  size: number | null;
  /**
   * Pages
   */
  pages?: number | null;
};

/**
 * TimelineBucket
 */
export type TimelineBucket = {
  /**
   * Bucket
   */
  bucket: string;
  /**
   * Count
   */
  count: number;
  /**
   * Anomaly Count
   */
  anomaly_count: number;
};

/**
 * TopIP
 */
export type TopIp = {
  /**
   * Source Ip
   */
  source_ip: string;
  /**
   * Count
   */
  count: number;
  /**
   * Anomaly Count
   */
  anomaly_count: number;
};

/**
 * UploadResponse
 */
export type UploadResponse = {
  file: LogFileRead;
  /**
   * Parsed
   */
  parsed: number;
  /**
   * Skipped
   */
  skipped: number;
  /**
   * Anomalies
   */
  anomalies: number;
};

/**
 * UserCreate
 */
export type UserCreate = {
  /**
   * Email
   */
  email: string;
  /**
   * Password
   */
  password: string;
  /**
   * Is Active
   */
  is_active?: boolean | null;
  /**
   * Is Superuser
   */
  is_superuser?: boolean | null;
  /**
   * Is Verified
   */
  is_verified?: boolean | null;
};

/**
 * UserRead
 */
export type UserRead = {
  /**
   * Id
   */
  id: string;
  /**
   * Email
   */
  email: string;
  /**
   * Is Active
   */
  is_active?: boolean;
  /**
   * Is Superuser
   */
  is_superuser?: boolean;
  /**
   * Is Verified
   */
  is_verified?: boolean;
};

/**
 * UserUpdate
 */
export type UserUpdate = {
  /**
   * Password
   */
  password?: string | null;
  /**
   * Email
   */
  email?: string | null;
  /**
   * Is Active
   */
  is_active?: boolean | null;
  /**
   * Is Superuser
   */
  is_superuser?: boolean | null;
  /**
   * Is Verified
   */
  is_verified?: boolean | null;
};

/**
 * ValidationError
 */
export type ValidationError = {
  /**
   * Location
   */
  loc: Array<string | number>;
  /**
   * Message
   */
  msg: string;
  /**
   * Error Type
   */
  type: string;
};

/**
 * Body_auth-auth:jwt.login
 */
export type Login = {
  /**
   * Grant Type
   */
  grant_type?: string | null;
  /**
   * Username
   */
  username: string;
  /**
   * Password
   */
  password: string;
  /**
   * Scope
   */
  scope?: string;
  /**
   * Client Id
   */
  client_id?: string | null;
  /**
   * Client Secret
   */
  client_secret?: string | null;
};

export type AuthJwtLoginData = {
  body: Login;
  path?: never;
  query?: never;
  url: "/auth/jwt/login";
};

export type AuthJwtLoginErrors = {
  /**
   * Bad Request
   */
  400: ErrorModel;
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type AuthJwtLoginError = AuthJwtLoginErrors[keyof AuthJwtLoginErrors];

export type AuthJwtLoginResponses = {
  /**
   * Successful Response
   */
  200: BearerResponse;
};

export type AuthJwtLoginResponse =
  AuthJwtLoginResponses[keyof AuthJwtLoginResponses];

export type AuthJwtLogoutData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/auth/jwt/logout";
};

export type AuthJwtLogoutErrors = {
  /**
   * Missing token or inactive user.
   */
  401: unknown;
};

export type AuthJwtLogoutResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type RegisterRegisterData = {
  body: UserCreate;
  path?: never;
  query?: never;
  url: "/auth/register";
};

export type RegisterRegisterErrors = {
  /**
   * Bad Request
   */
  400: ErrorModel;
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type RegisterRegisterError =
  RegisterRegisterErrors[keyof RegisterRegisterErrors];

export type RegisterRegisterResponses = {
  /**
   * Successful Response
   */
  201: UserRead;
};

export type RegisterRegisterResponse =
  RegisterRegisterResponses[keyof RegisterRegisterResponses];

export type ResetForgotPasswordData = {
  body: BodyAuthResetForgotPassword;
  path?: never;
  query?: never;
  url: "/auth/forgot-password";
};

export type ResetForgotPasswordErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type ResetForgotPasswordError =
  ResetForgotPasswordErrors[keyof ResetForgotPasswordErrors];

export type ResetForgotPasswordResponses = {
  /**
   * Successful Response
   */
  202: unknown;
};

export type ResetResetPasswordData = {
  body: BodyAuthResetResetPassword;
  path?: never;
  query?: never;
  url: "/auth/reset-password";
};

export type ResetResetPasswordErrors = {
  /**
   * Bad Request
   */
  400: ErrorModel;
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type ResetResetPasswordError =
  ResetResetPasswordErrors[keyof ResetResetPasswordErrors];

export type ResetResetPasswordResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type VerifyRequestTokenData = {
  body: BodyAuthVerifyRequestToken;
  path?: never;
  query?: never;
  url: "/auth/request-verify-token";
};

export type VerifyRequestTokenErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type VerifyRequestTokenError =
  VerifyRequestTokenErrors[keyof VerifyRequestTokenErrors];

export type VerifyRequestTokenResponses = {
  /**
   * Successful Response
   */
  202: unknown;
};

export type VerifyVerifyData = {
  body: BodyAuthVerifyVerify;
  path?: never;
  query?: never;
  url: "/auth/verify";
};

export type VerifyVerifyErrors = {
  /**
   * Bad Request
   */
  400: ErrorModel;
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type VerifyVerifyError = VerifyVerifyErrors[keyof VerifyVerifyErrors];

export type VerifyVerifyResponses = {
  /**
   * Successful Response
   */
  200: UserRead;
};

export type VerifyVerifyResponse =
  VerifyVerifyResponses[keyof VerifyVerifyResponses];

export type UsersCurrentUserData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/users/me";
};

export type UsersCurrentUserErrors = {
  /**
   * Missing token or inactive user.
   */
  401: unknown;
};

export type UsersCurrentUserResponses = {
  /**
   * Successful Response
   */
  200: UserRead;
};

export type UsersCurrentUserResponse =
  UsersCurrentUserResponses[keyof UsersCurrentUserResponses];

export type UsersPatchCurrentUserData = {
  body: UserUpdate;
  path?: never;
  query?: never;
  url: "/users/me";
};

export type UsersPatchCurrentUserErrors = {
  /**
   * Bad Request
   */
  400: ErrorModel;
  /**
   * Missing token or inactive user.
   */
  401: unknown;
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type UsersPatchCurrentUserError =
  UsersPatchCurrentUserErrors[keyof UsersPatchCurrentUserErrors];

export type UsersPatchCurrentUserResponses = {
  /**
   * Successful Response
   */
  200: UserRead;
};

export type UsersPatchCurrentUserResponse =
  UsersPatchCurrentUserResponses[keyof UsersPatchCurrentUserResponses];

export type UsersDeleteUserData = {
  body?: never;
  path: {
    /**
     * Id
     */
    id: string;
  };
  query?: never;
  url: "/users/{id}";
};

export type UsersDeleteUserErrors = {
  /**
   * Missing token or inactive user.
   */
  401: unknown;
  /**
   * Not a superuser.
   */
  403: unknown;
  /**
   * The user does not exist.
   */
  404: unknown;
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type UsersDeleteUserError =
  UsersDeleteUserErrors[keyof UsersDeleteUserErrors];

export type UsersDeleteUserResponses = {
  /**
   * Successful Response
   */
  204: void;
};

export type UsersDeleteUserResponse =
  UsersDeleteUserResponses[keyof UsersDeleteUserResponses];

export type UsersUserData = {
  body?: never;
  path: {
    /**
     * Id
     */
    id: string;
  };
  query?: never;
  url: "/users/{id}";
};

export type UsersUserErrors = {
  /**
   * Missing token or inactive user.
   */
  401: unknown;
  /**
   * Not a superuser.
   */
  403: unknown;
  /**
   * The user does not exist.
   */
  404: unknown;
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type UsersUserError = UsersUserErrors[keyof UsersUserErrors];

export type UsersUserResponses = {
  /**
   * Successful Response
   */
  200: UserRead;
};

export type UsersUserResponse = UsersUserResponses[keyof UsersUserResponses];

export type UsersPatchUserData = {
  body: UserUpdate;
  path: {
    /**
     * Id
     */
    id: string;
  };
  query?: never;
  url: "/users/{id}";
};

export type UsersPatchUserErrors = {
  /**
   * Bad Request
   */
  400: ErrorModel;
  /**
   * Missing token or inactive user.
   */
  401: unknown;
  /**
   * Not a superuser.
   */
  403: unknown;
  /**
   * The user does not exist.
   */
  404: unknown;
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type UsersPatchUserError =
  UsersPatchUserErrors[keyof UsersPatchUserErrors];

export type UsersPatchUserResponses = {
  /**
   * Successful Response
   */
  200: UserRead;
};

export type UsersPatchUserResponse =
  UsersPatchUserResponses[keyof UsersPatchUserResponses];

export type ReadItemData = {
  body?: never;
  path?: never;
  query?: {
    /**
     * Page
     * Page number
     */
    page?: number;
    /**
     * Size
     * Page size
     */
    size?: number;
  };
  url: "/items/";
};

export type ReadItemErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type ReadItemError = ReadItemErrors[keyof ReadItemErrors];

export type ReadItemResponses = {
  /**
   * Successful Response
   */
  200: PageItemRead;
};

export type ReadItemResponse = ReadItemResponses[keyof ReadItemResponses];

export type CreateItemData = {
  body: ItemCreate;
  path?: never;
  query?: never;
  url: "/items/";
};

export type CreateItemErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type CreateItemError = CreateItemErrors[keyof CreateItemErrors];

export type CreateItemResponses = {
  /**
   * Successful Response
   */
  200: ItemRead;
};

export type CreateItemResponse = CreateItemResponses[keyof CreateItemResponses];

export type DeleteItemData = {
  body?: never;
  path: {
    /**
     * Item Id
     */
    item_id: string;
  };
  query?: never;
  url: "/items/{item_id}";
};

export type DeleteItemErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type DeleteItemError = DeleteItemErrors[keyof DeleteItemErrors];

export type DeleteItemResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type UploadLogFileData = {
  body: BodyLogsUploadLogFile;
  path?: never;
  query?: never;
  url: "/logs/upload";
};

export type UploadLogFileErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type UploadLogFileError = UploadLogFileErrors[keyof UploadLogFileErrors];

export type UploadLogFileResponses = {
  /**
   * Successful Response
   */
  200: UploadResponse;
};

export type UploadLogFileResponse =
  UploadLogFileResponses[keyof UploadLogFileResponses];

export type ListLogFilesData = {
  body?: never;
  path?: never;
  query?: {
    /**
     * Page
     * Page number
     */
    page?: number;
    /**
     * Size
     * Page size
     */
    size?: number;
  };
  url: "/logs/files";
};

export type ListLogFilesErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type ListLogFilesError = ListLogFilesErrors[keyof ListLogFilesErrors];

export type ListLogFilesResponses = {
  /**
   * Successful Response
   */
  200: PageLogFileRead;
};

export type ListLogFilesResponse =
  ListLogFilesResponses[keyof ListLogFilesResponses];

export type ListLogEntriesData = {
  body?: never;
  path: {
    /**
     * File Id
     */
    file_id: string;
  };
  query?: {
    /**
     * Only Anomalies
     */
    only_anomalies?: boolean;
    /**
     * Page
     * Page number
     */
    page?: number;
    /**
     * Size
     * Page size
     */
    size?: number;
  };
  url: "/logs/files/{file_id}/entries";
};

export type ListLogEntriesErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type ListLogEntriesError =
  ListLogEntriesErrors[keyof ListLogEntriesErrors];

export type ListLogEntriesResponses = {
  /**
   * Successful Response
   */
  200: PageLogEntryRead;
};

export type ListLogEntriesResponse =
  ListLogEntriesResponses[keyof ListLogEntriesResponses];

export type GetLogFileSummaryData = {
  body?: never;
  path: {
    /**
     * File Id
     */
    file_id: string;
  };
  query?: never;
  url: "/logs/files/{file_id}/summary";
};

export type GetLogFileSummaryErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type GetLogFileSummaryError =
  GetLogFileSummaryErrors[keyof GetLogFileSummaryErrors];

export type GetLogFileSummaryResponses = {
  /**
   * Successful Response
   */
  200: LogFileSummary;
};

export type GetLogFileSummaryResponse =
  GetLogFileSummaryResponses[keyof GetLogFileSummaryResponses];

export type DeleteLogFileData = {
  body?: never;
  path: {
    /**
     * File Id
     */
    file_id: string;
  };
  query?: never;
  url: "/logs/files/{file_id}";
};

export type DeleteLogFileErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type DeleteLogFileError = DeleteLogFileErrors[keyof DeleteLogFileErrors];

export type DeleteLogFileResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type ExplainLogEntryData = {
  body?: never;
  path: {
    /**
     * Entry Id
     */
    entry_id: string;
  };
  query?: never;
  url: "/logs/entries/{entry_id}/explain";
};

export type ExplainLogEntryErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type ExplainLogEntryError =
  ExplainLogEntryErrors[keyof ExplainLogEntryErrors];

export type ExplainLogEntryResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type CompareModelsData = {
  body?: never;
  path?: never;
  query?: {
    /**
     * Sample
     */
    sample?: number;
    /**
     * Page
     */
    page?: number;
    /**
     * Size
     */
    size?: number;
    /**
     * Threshold
     */
    threshold?: number | null;
  };
  url: "/models/compare";
};

export type CompareModelsErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type CompareModelsError = CompareModelsErrors[keyof CompareModelsErrors];

export type CompareModelsResponses = {
  /**
   * Response Models-Compare Models
   * Successful Response
   */
  200: {
    [key: string]: unknown;
  };
};

export type CompareModelsResponse =
  CompareModelsResponses[keyof CompareModelsResponses];

export type ClientOptions = {
  baseURL: `${string}://${string}` | (string & {});
};
